//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jypeli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowsPhoneResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowsPhoneResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jypeli.WindowsPhoneResources", typeof(WindowsPhoneResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AsRifle {
            get {
                object obj = ResourceManager.GetObject("AsRifle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Auto {
            get {
                object obj = ResourceManager.GetObject("Auto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bullet {
            get {
                object obj = ResourceManager.GetObject("Bullet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cannon {
            get {
                object obj = ResourceManager.GetObject("Cannon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CannonBall {
            get {
                object obj = ResourceManager.GetObject("CannonBall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CannonFire {
            get {
                object obj = ResourceManager.GetObject("CannonFire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] explosion {
            get {
                object obj = ResourceManager.GetObject("explosion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] explosion2 {
            get {
                object obj = ResourceManager.GetObject("explosion2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] explosionSound {
            get {
                object obj = ResourceManager.GetObject("explosionSound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Grenade {
            get {
                object obj = ResourceManager.GetObject("Grenade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] implosionSound {
            get {
                object obj = ResourceManager.GetObject("implosionSound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LargeFont {
            get {
                object obj = ResourceManager.GetObject("LargeFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LargeFontBold {
            get {
                object obj = ResourceManager.GetObject("LargeFontBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] laser {
            get {
                object obj = ResourceManager.GetObject("laser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MediumFont {
            get {
                object obj = ResourceManager.GetObject("MediumFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MediumFontBold {
            get {
                object obj = ResourceManager.GetObject("MediumFontBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MGAttack {
            get {
                object obj = ResourceManager.GetObject("MGAttack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlasmaAttack {
            get {
                object obj = ResourceManager.GetObject("PlasmaAttack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlasmaCannon {
            get {
                object obj = ResourceManager.GetObject("PlasmaCannon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SmallFont {
            get {
                object obj = ResourceManager.GetObject("SmallFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SmallFontBold {
            get {
                object obj = ResourceManager.GetObject("SmallFontBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] smoke {
            get {
                object obj = ResourceManager.GetObject("smoke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tank {
            get {
                object obj = ResourceManager.GetObject("Tank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
